/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author ASUS
 */
public class PilihGambarbutton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarbutton
     */
    public PilihGambarbutton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        btncamera = new javax.swing.JButton();
        btnearphone = new javax.swing.JButton();
        btnlaptop = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        lbcamera = new javax.swing.JLabel();
        lcearphone = new javax.swing.JLabel();
        lblaptop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btncamera.setText("Camera");
        btncamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncameraActionPerformed(evt);
            }
        });

        btnearphone.setText("Earphone");
        btnearphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnearphoneActionPerformed(evt);
            }
        });

        btnlaptop.setText("Laptop");
        btnlaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaptopActionPerformed(evt);
            }
        });

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btncamera)
                .addGap(61, 61, 61)
                .addComponent(btnearphone)
                .addGap(57, 57, 57)
                .addComponent(btnlaptop)
                .addGap(42, 42, 42)
                .addComponent(btnexit)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncamera)
                    .addComponent(btnearphone)
                    .addComponent(btnlaptop)
                    .addComponent(btnexit))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        lbcamera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout/Camera.jpg"))); // NOI18N
        imagePanel.add(lbcamera, "0");

        lcearphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout/Earphone.jpeg"))); // NOI18N
        imagePanel.add(lcearphone, "1");

        lblaptop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout/Laptop.jpg"))); // NOI18N
        imagePanel.add(lblaptop, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncameraActionPerformed
      CardLayout cl = (CardLayout) (imagePanel.getLayout());
      cl.show(imagePanel, "0");
    }//GEN-LAST:event_btncameraActionPerformed

    private void btnearphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnearphoneActionPerformed
      CardLayout cl = (CardLayout) (imagePanel.getLayout());
      cl.show(imagePanel, "1");
    }//GEN-LAST:event_btnearphoneActionPerformed

    private void btnlaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaptopActionPerformed
       CardLayout cl = (CardLayout) (imagePanel.getLayout());
      cl.show(imagePanel, "2");
    }//GEN-LAST:event_btnlaptopActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarbutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarbutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarbutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarbutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarbutton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncamera;
    private javax.swing.JButton btnearphone;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlaptop;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel lbcamera;
    private javax.swing.JLabel lblaptop;
    private javax.swing.JLabel lcearphone;
    // End of variables declaration//GEN-END:variables
}
